# Generated by Django 4.1 on 2022-08-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
