# Generated by Django 4.1 on 2022-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_post_updated_by_post_updated_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="updated_dt",
            field=models.DateTimeField(null=True),
        ),
    ]
